<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>OpcDaToUaGateway.Watchdog</AssemblyName>
    <RootNamespace>OpcDaToUaGateway.Watchdog</RootNamespace>
    <PlatformTarget>x86</PlatformTarget>
    <LangVersion>8.0</LangVersion>
    <ApplicationIcon>..\opc-da-opc-ua.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>2.7.0</Version>
    <AssemblyVersion>2.7.0.0</AssemblyVersion>
    <FileVersion>2.7.0.0</FileVersion>
    <Company>OPC DA to UA Gateway</Company>
    <Product>OPC DA to OPC UA Gateway Watchdog</Product>
    <Description>OPC DA 到 OPC UA 网关看门狗进程监控</Description>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>

</Project>
